//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int IDMessage { get; set; }
        public Nullable<int> IDParent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string MessegeType { get; set; }
        public Nullable<int> IDChild { get; set; }
    
        public virtual Parent Parent { get; set; }
    }
}
